[package]
name = "gdmp-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enet = { path = "./enet-rs" }
anyhow = "1.0.71"
prost = "0.11.9"

[build-dependencies]
prost-build = "0.11.9"